# Generated by Django 2.1.5 on 2019-05-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todotag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='todotag',
            name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(to='todos.Tag'),
        ),
        migrations.DeleteModel(
            name='TodoTag',
        ),
    ]
