# Generated by Django 2.1.5 on 2019-05-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='file_upload',
            field=models.FileField(upload_to='media'),
        ),
    ]
